### ISSUE TITLE
FAQ: Why can I not use cracked alts on premium servers?

### ISSUE THREAD

**Issue by Alexander01998** [Wurst-Imperium/WurstClient.net#133]

**Comment by Umaruun** [comment]
This is because PREMIUM-Servers are PREMIUM only.
Premium means paid Minecraft. These paid accounts are registered in the Mojang Servers.
Cracked Accounts run on your device. That means a premium server is unable to verify a cracked account, because:
1. The account doesn't exist
or
2. The authentication stuff is invalid.
