### ISSUE TITLE
Debugging Wurst

### ISSUE THREAD

**Issue by scriptinator** [Wurst-Imperium/WurstClient.net#15]
The page on the wiki is a heavily modified version of my wiki page and is just the same as the old wiki page. Also recompilation section is deleted. I will put some of @Alexander01998's warnings into the wiki page I have created, but I believe the tutorial should mainly how it should be so beginners (Like me) can figure out how to debug Wurst in Eclipse. I did not need to know Java to add in a simple mod to Wurst. I simply looked at how the previous mods were sorted out. I believe the beginners need a better tutorial

**Comment by Alexander01998** [comment]
> The page on the wiki is a heavily modified version of my wiki page

Yes, I cleaned it up. You can see that in the commit history.
I want to make sure that all wiki pages have a high quality. The "heavy" modification is mostly due to "heavy" Markdown errors and unnecessary explanations (see below).

> but I believe the tutorial should mainly how it should be so beginners

The tutorial is only intended for people who are familiar with Eclipse, Git and the MCP. Other than that, it works for anyone, regardless of their level of experience.

> I did not need to know Java to add in a simple mod to Wurst.

The tutorial doesn't involve any Java, therefore being familiar with Java is not required to understand it.

**Comment by scriptinator** [comment]
I was quite familiar with Eclipse, but it took me ages to figure out how to debug Wurst in Eclipse. I am not alone in this situation either, Nitrogeon-Dioxide also said it took him a while as well. These "unnecessary explanations" are to clarify so people don't get stuck like me. This also seems like the old page then.

**Comment by scriptinator** [comment]
You said it works for anyone-it doesnt. Even if they are familiar with these things the tutorial is not descriptive enough
